services:
    db:
        image: postgres:17.2
        container_name: bancoconectelo
        ports:
            - "8080:5432"
        environment:
            - POSTGRES_PASSWORD=root
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - conectelo-network

    api:
        build: .
        container_name: conectelo-api
        depends_on:
            - db
        ports:
            - "5000:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ConectEloDB;Username=postgres;Password=root
            - Jwt__Key=R0X6tIjlSzjFKDpgB8MAHn5bAeyEzefzBPa5+GVrSNg
            - Jwt__Issuer=ConectElo
            - Jwt__Audience=ConectElo
            - Jwt__ExpiresInHours=8
        volumes:
            - ./uploads:/app/uploads
        networks:
            - conectelo-network

volumes:
    postgres_data:

networks:
    conectelo-network:
        driver: bridge