// <auto-generated />
using System;
using ConectElo.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConectElo.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701014140_AdicionarQuizAmigoSecreto")]
    partial class AdicionarQuizAmigoSecreto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConectElo.Domain.Areas.Comunicacao.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Anonima")
                        .HasColumnType("boolean");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HorarioEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MidiaUrl")
                        .HasColumnType("text");

                    b.Property<int>("TipoMidia")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Comunicacao.Entities.Notificacoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotificacaoLida")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoNotificacao")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ItensListaDesejos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListaDesejosId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListaDesejosId");

                    b.HasIndex("ReservadoPorId");

                    b.ToTable("ItensListaDesejos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ListaDesejos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ListaDesejos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.MensagemAnonima", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HorarioEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParticipanteTipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResultadoSorteioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoSorteioId");

                    b.ToTable("MensagensAnonimas");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.OpcaoQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Emoji")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("PerguntaQuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaQuizId");

                    b.ToTable("OpcoesQuiz");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000001"),
                            Emoji = "📚",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000001"),
                            Texto = "Algo útil"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000002"),
                            Emoji = "😂",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000001"),
                            Texto = "Algo engraçado"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000003"),
                            Emoji = "✨",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000001"),
                            Texto = "Algo criativo"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000004"),
                            Emoji = "❤️",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000001"),
                            Texto = "Algo com significado"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000005"),
                            Emoji = "🎉",
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000001"),
                            Texto = "Surpresa total"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000006"),
                            Emoji = "🍫",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000002"),
                            Texto = "Consumível"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000007"),
                            Emoji = "🧸",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000002"),
                            Texto = "Objeto"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000008"),
                            Emoji = "🎟️",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000002"),
                            Texto = "Experiência"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000009"),
                            Emoji = "💌",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000002"),
                            Texto = "Algo feito à mão"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000000a"),
                            Emoji = "📚",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Texto = "Livros"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000000b"),
                            Emoji = "☕",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Texto = "Café/Chá"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000000c"),
                            Emoji = "🎮",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Texto = "Games"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000000d"),
                            Emoji = "🎧",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Texto = "Música"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000000e"),
                            Emoji = "👕",
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Texto = "Roupas"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000000f"),
                            Emoji = "🏠",
                            Ordem = 6,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Texto = "Casa"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000010"),
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Texto = "Pequeno e útil"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000011"),
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Texto = "Diferente"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000012"),
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Texto = "Premium"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000013"),
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Texto = "Engraçado"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000014"),
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Texto = "Minimalista"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000015"),
                            Emoji = "🎨",
                            Ordem = 6,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Texto = "Estilo"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000016"),
                            Emoji = "⚫",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000005"),
                            Texto = "Minimalista"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000017"),
                            Emoji = "🌈",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000005"),
                            Texto = "Colorido"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000018"),
                            Emoji = "🪵",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000005"),
                            Texto = "Natural"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000019"),
                            Emoji = "✨",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000005"),
                            Texto = "Moderno"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000001a"),
                            Emoji = "🎮",
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000005"),
                            Texto = "Geek"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000001b"),
                            Emoji = "⚫",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Texto = "Preto"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000001c"),
                            Emoji = "⚪",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Texto = "Branco"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000001d"),
                            Emoji = "🔵",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Texto = "Azul"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000001e"),
                            Emoji = "🟢",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Texto = "Verde"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000001f"),
                            Emoji = "🔴",
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Texto = "Vermelho"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000020"),
                            Emoji = "🟣",
                            Ordem = 6,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Texto = "Roxo"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000021"),
                            Emoji = "🏠",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000007"),
                            Texto = "Caseiro"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000022"),
                            Emoji = "✈️",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000007"),
                            Texto = "Explorador"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000023"),
                            Emoji = "☕",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000007"),
                            Texto = "Relax"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000024"),
                            Emoji = "🏃",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000007"),
                            Texto = "Ativo"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000025"),
                            Emoji = "🍕",
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000007"),
                            Texto = "Hábitos"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000026"),
                            Emoji = "🌅",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000008"),
                            Texto = "Manhã"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000027"),
                            Emoji = "☀️",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000008"),
                            Texto = "Tarde"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000028"),
                            Emoji = "🌙",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000008"),
                            Texto = "Noite"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000029"),
                            Emoji = "🌃",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000008"),
                            Texto = "Madrugada"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000002a"),
                            Emoji = "🎬",
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000009"),
                            Texto = "Filmes"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000002b"),
                            Emoji = "🎮",
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000009"),
                            Texto = "Jogos"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000002c"),
                            Emoji = "🍽️",
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000009"),
                            Texto = "Comer fora"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000002d"),
                            Emoji = "📚",
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000009"),
                            Texto = "Ler"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000002e"),
                            Emoji = "💤",
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-000000000009"),
                            Texto = "Descansar"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-00000000002f"),
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000a"),
                            Texto = "Perfume"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000030"),
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000a"),
                            Texto = "Roupa"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000031"),
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000a"),
                            Texto = "Decoração"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000032"),
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000a"),
                            Texto = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000033"),
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000a"),
                            Texto = "Vale-presente"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000034"),
                            Ordem = 1,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000b"),
                            Texto = "Golden retriever"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000035"),
                            Ordem = 2,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000b"),
                            Texto = "Gato"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000036"),
                            Ordem = 3,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000b"),
                            Texto = "Coruja"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000037"),
                            Ordem = 4,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000b"),
                            Texto = "Capivara"
                        },
                        new
                        {
                            Id = new Guid("b2f2c0d0-0000-0000-0000-000000000038"),
                            Ordem = 5,
                            PerguntaQuizId = new Guid("b1f1c0d0-0000-0000-0000-00000000000b"),
                            Texto = "Panda"
                        });
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.PerguntaAmigoSecreto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OpcaoRespostaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerguntaQuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PerguntadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResultadoSorteioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpcaoRespostaId");

                    b.HasIndex("PerguntaQuizId");

                    b.HasIndex("ResultadoSorteioId");

                    b.ToTable("PerguntasAmigoSecreto");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.PerguntaQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PerguntasQuiz");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000001"),
                            Ativa = true,
                            Texto = "Qual presente te deixa mais feliz?"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000002"),
                            Ativa = true,
                            Texto = "Você prefere ganhar…"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000003"),
                            Ativa = true,
                            Texto = "Qual categoria mais combina com você?"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000004"),
                            Ativa = true,
                            Texto = "Seu tipo de presente ideal é…"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000005"),
                            Ativa = true,
                            Texto = "Qual sua estética?"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000006"),
                            Ativa = true,
                            Texto = "Escolha uma cor"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000007"),
                            Ativa = true,
                            Texto = "Você é mais…"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000008"),
                            Ativa = true,
                            Texto = "Seu momento favorito do dia"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-000000000009"),
                            Ativa = true,
                            Texto = "Final de semana perfeito"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-00000000000a"),
                            Ativa = true,
                            Texto = "O que você menos gosta de ganhar?"
                        },
                        new
                        {
                            Id = new Guid("b1f1c0d0-0000-0000-0000-00000000000b"),
                            Ativa = true,
                            Texto = "Qual energia combina com você?"
                        });
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ResultadoSorteio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PresenteadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecebedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("PresenteadorId");

                    b.HasIndex("RecebedorId");

                    b.ToTable("ResultadoSorteios");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Eventos.Entities.ConviteEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenConvite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConviteEventos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Eventos.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Criador")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("FotoCapaUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Localizacao")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Criador");

                    b.HasIndex("GrupoId");

                    b.ToTable("Eventos");

                    b.HasDiscriminator().HasValue("Evento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Geral.Entities.BanimentoGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BanidoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataBanimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BanimentoGrupo");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Geral.Entities.ConfirmacaoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConfirmacaoEventos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Geral.Entities.SolicitacaoEntrada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitacaoEntrada");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.GaleriaFotos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventosId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GaleriaFotos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoConvite")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CodigoConviteExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImgGrupo")
                        .HasColumnType("text");

                    b.Property<Guid>("MuralId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Privado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TipoExpiracaoEConvite")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConvite")
                        .IsUnique()
                        .HasDatabaseName("IX_Grupos_CodigoConvite")
                        .HasFilter("\"CodigoConvite\" IS NOT NULL");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Interesse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000001"),
                            Nome = "Café"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000002"),
                            Nome = "Sushi"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000003"),
                            Nome = "Cozinhar"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000004"),
                            Nome = "Vinho"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000005"),
                            Nome = "Música"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000006"),
                            Nome = "Filmes"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000007"),
                            Nome = "Livros"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000008"),
                            Nome = "Games"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000009"),
                            Nome = "Academia"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000000a"),
                            Nome = "Corrida"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000000b"),
                            Nome = "Futebol"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000000c"),
                            Nome = "Boxe"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000000d"),
                            Nome = "Praia"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000000e"),
                            Nome = "Viagens"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000000f"),
                            Nome = "Fotografia"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000010"),
                            Nome = "Arte"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000011"),
                            Nome = "Museus"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000012"),
                            Nome = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000013"),
                            Nome = "Programação"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000014"),
                            Nome = "Carros"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000015"),
                            Nome = "Moda"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000016"),
                            Nome = "Tatuagens"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000017"),
                            Nome = "Cachorros"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000018"),
                            Nome = "Jardinagem"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-000000000019"),
                            Nome = "Jogos de tabuleiro"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000001a"),
                            Nome = "Podcasts"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000001b"),
                            Nome = "Astrologia"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000001c"),
                            Nome = "Festivais"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000001d"),
                            Nome = "Baladas"
                        },
                        new
                        {
                            Id = new Guid("a1f1c0d0-0000-0000-0000-00000000001e"),
                            Nome = "Stand-up Comedy"
                        });
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.MembrosGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_MembrosGrupo_UsuarioId");

                    b.ToTable("membrosGrupos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Mural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Mural");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Postagens", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataPostagem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MuralId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("MuralId", "DataPostagem")
                        .HasDatabaseName("IX_Postagens_MuralId_DataPostagem");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacaoConta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDelecao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FotoPerdilUrl")
                        .HasColumnType("text");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("UsuarioAtivo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InteresseUsuario", b =>
                {
                    b.Property<Guid>("InteressesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuariosId")
                        .HasColumnType("uuid");

                    b.HasKey("InteressesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("InteresseUsuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.AmigoSecretoEvento", b =>
                {
                    b.HasBaseType("ConectElo.Domain.Areas.Eventos.Entities.Evento");

                    b.Property<DateTime?>("DataExecucaoSorteio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.Property<bool>("Sorteado")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusSorteio")
                        .HasColumnType("integer");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("AmigoSecretoEvento");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.AniversarioEvento", b =>
                {
                    b.HasBaseType("ConectElo.Domain.Areas.Eventos.Entities.Evento");

                    b.Property<int?>("Idade")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ListaDesejosId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeAniversariante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ListaDesejosId");

                    b.HasDiscriminator().HasValue("AniversarioEvento");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Comunicacao.Entities.Mensagem", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ItensListaDesejos", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.ListaDesejos", "ListaDesejos")
                        .WithMany("Itens")
                        .HasForeignKey("ListaDesejosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "ReservadoPor")
                        .WithMany()
                        .HasForeignKey("ReservadoPorId");

                    b.Navigation("ListaDesejos");

                    b.Navigation("ReservadoPor");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.MensagemAnonima", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.ResultadoSorteio", "ResultadoSorteio")
                        .WithMany("Mensagens")
                        .HasForeignKey("ResultadoSorteioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultadoSorteio");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.OpcaoQuiz", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.PerguntaQuiz", "PerguntaQuiz")
                        .WithMany("Opcoes")
                        .HasForeignKey("PerguntaQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerguntaQuiz");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.PerguntaAmigoSecreto", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.OpcaoQuiz", "OpcaoResposta")
                        .WithMany()
                        .HasForeignKey("OpcaoRespostaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.PerguntaQuiz", "PerguntaQuiz")
                        .WithMany()
                        .HasForeignKey("PerguntaQuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.ResultadoSorteio", "ResultadoSorteio")
                        .WithMany()
                        .HasForeignKey("ResultadoSorteioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcaoResposta");

                    b.Navigation("PerguntaQuiz");

                    b.Navigation("ResultadoSorteio");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ResultadoSorteio", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.AmigoSecretoEvento", "Evento")
                        .WithMany("Resultados")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Presenteador")
                        .WithMany()
                        .HasForeignKey("PresenteadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Recebedor")
                        .WithMany()
                        .HasForeignKey("RecebedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Presenteador");

                    b.Navigation("Recebedor");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Eventos.Entities.ConviteEvento", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Eventos.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Eventos.Entities.Evento", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "CriadorEvento")
                        .WithMany()
                        .HasForeignKey("Criador");

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadorEvento");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Geral.Entities.BanimentoGrupo", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "UsuarioBanido")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("UsuarioBanido");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Geral.Entities.ConfirmacaoEvento", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Eventos.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Geral.Entities.SolicitacaoEntrada", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.MembrosGrupo", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Grupo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Postagens", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("InteresseUsuario", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Interesse", null)
                        .WithMany()
                        .HasForeignKey("InteressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Social.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.AniversarioEvento", b =>
                {
                    b.HasOne("ConectElo.Domain.Areas.Dinamicas.Entities.ListaDesejos", "ListaDesejos")
                        .WithMany()
                        .HasForeignKey("ListaDesejosId");

                    b.Navigation("ListaDesejos");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ListaDesejos", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.PerguntaQuiz", b =>
                {
                    b.Navigation("Opcoes");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.ResultadoSorteio", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Social.Entities.Grupo", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ConectElo.Domain.Areas.Dinamicas.Entities.AmigoSecretoEvento", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
